export const theme = {
  colors: {
    primary: '#00374e',
    primaryContainer: '#0b4F6C',
    secondary: '#2c694e',
    secondaryContainer: '#aeeecb',
    tertiary: '#5a046b',
    tertiaryContainer: '#742684',
    background: '#fcf9f8',
    surface: '#fcf9f8',
    surfaceContainer: '#f0eded',
    surfaceContainerLow: '#f6f3f2',
    surfaceContainerHigh: '#eae7e7',
    surfaceContainerLowest: '#ffffff',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#8ac0e1',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#316e52',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#f199fe',
    onBackground: '#1c1b1b',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#41484d',
    error: '#ba1a1a',
    errorContainer: '#ffdad6',
    onError: '#ffffff',
    onErrorContainer: '#93000a',
    outline: '#71787e',
    outlineVariant: '#c0c7ce',
    inverseSurface: '#313030',
    inverseOnSurface: '#f3f0ef',
    inversePrimary: '#97cdef',
    surfaceTint: '#2a6482',
    surfaceDim: '#dcd9d9',
    surfaceBright: '#fcf9f8',
    surfaceVariant: '#e5e2e1',
    surfaceContainerHighest: '#e5e2e1',
    primaryFixed: '#c5e7ff',
    primaryFixedDim: '#97cdef',
    secondaryFixed: '#b1f0ce',
    secondaryFixedDim: '#95d4b3',
    tertiaryFixed: '#fed6ff',
    tertiaryFixedDim: '#f6adff',
    onPrimaryFixed: '#001e2d',
    onPrimaryFixedVariant: '#054c69',
    onSecondaryFixed: '#002114',
    onSecondaryFixedVariant: '#0e5138',
    onTertiaryFixed: '#350041',
    onTertiaryFixedVariant: '#712281',
  },
  fonts: {
    display: 'Work Sans',
    headline: 'Work Sans',
    body: 'Public Sans',
    label: 'Public Sans',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
};

export const colors = theme.colors;
export const spacing = theme.spacing;
export const borderRadius = theme.borderRadius;