/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#643f00",
        "outline-variant": "#c0c9bb",
        "surface-container": "#eeeeee",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#410003",
        "on-primary-fixed-variant": "#0c5216",
        "surface-tint": "#2a6b2c",
        "primary": "#00450d",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed": "#ffdad6",
        "inverse-on-surface": "#f1f1f1",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#ffb957",
        "outline": "#717a6d",
        "on-background": "#1a1c1c",
        "tertiary": "#7c000a",
        "surface-container-low": "#f3f3f3",
        "on-primary-container": "#90d689",
        "primary-container": "#1b5e20",
        "on-tertiary-fixed-variant": "#93000e",
        "tertiary-fixed-dim": "#ffb4ac",
        "on-surface": "#1a1c1c",
        "on-secondary-container": "#694300",
        "inverse-surface": "#2f3131",
        "on-tertiary-container": "#ffb2aa",
        "tertiary-container": "#a60a15",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffddb5",
        "on-secondary-fixed": "#2a1800",
        "on-surface-variant": "#41493e",
        "surface-variant": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fcab28",
        "secondary": "#835400",
        "surface-dim": "#dadada",
        "inverse-primary": "#91d78a",
        "on-error-container": "#93000a",
        "background": "#f9f9f9",
        "on-primary": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#91d78a",
        "primary-fixed": "#acf4a4",
        "on-primary-fixed": "#002203",
        "surface": "#f9f9f9",
        "surface-container-highest": "#e2e2e2",
        "on-error": "#ffffff"
      },
      fontFamily: {
        headline: ["Public Sans"],
        body: ["Public Sans"],
        label: ["Public Sans"]
      }
    },
  },
  plugins: [],
}
